### PR TITLE
add another test

### PR DESCRIPTION
**Pull request by bubbomb**

### CODE REVIEW

**Review by sorenbybee — DISMISSED** [review]
dora

**Review by MrK700 — APPROVED** [review]
NO REALISTIC SHREK

**Review by MrK700 — DISMISSED** [review]
st,small,507x507-pad,600x600,f8f8f8

**Review by sorenbybee — APPROVED** [review]
finn

**Review by MrK700 — APPROVED** [review]
unnamed

**Comment by sorenbybee** [comment]
bob

**Pull request merged**
