### PR TITLE
Added new test, moved binaryconvert to new file, updated README

### PR DESCRIPTION
**Pull request by rikerevans360**

### CODE REVIEW

**Review by DonGitSchool — APPROVED** [review]
Working, very nice

**Comment by sorenbybee** [comment]
Just heads up this code actually prevents the flask app from running despite all tests passing. I made this exact mistake myself.

**Comment by DonGitSchool** [comment]
it seems to work fine on the convertToBinary endpoint and runs.
image
image
image
Is there something missing we should test?

**Comment by sorenbybee** [comment]
Oh my mistake I guess running "flask run" instead of "python3 -m flask run"  will result in an error. LOL

**Pull request merged**
